### ISSUE TITLE
wrong variable

### ISSUE THREAD

**Issue by ben10ben** [lucidrains/iTransformer#17]
Hi, there is an issue with iTransformer.py in line 210 and the other iTransformer implementations as well. 

assert targets.shape == pred_list.shape

should be changed to

assert target.shape == pred.shape

**Comment by lucidrains** [comment]
@ben10ben hey! thanks for catching this, should be fixed

have you tried any of the variants?

**Comment by lucidrains** [comment]
nice! looks great! thank you for relaying 💯
