### ISSUE TITLE
hyperparameters cause issues

### ISSUE THREAD

**Issue by ben10ben** [lucidrains/iTransformer#18]
I'm running my hyperparameter tuning with iTransformer.py and found some issues.

attend.py
134:  attn = attn.type(dtype) # causes reference before assignment error

solution?
if self.causal:
    attn = attn.type(dtype)
else:
    attn = attn.type(sim.dtype)

revin.py  # using num_tokens_per_variate != 1
44: unscaled_output = (scaled_output - self.beta) / clamped_gamma

scaled_output is always a factor of the num_tokens variable

scaled_ouput torch.Size([32, 60, 641])
beta torch.Size([30, 1])
clamped_gamma torch.Size([30, 1])

Did not figure out a solution, yet.

**Comment by lucidrains** [comment]
@ben10ben do you want to see if 0.4.4 fixes the issue? also, do let me know if my intuition about having more surface area for attention proves correct (setting `num_tokens_per_variate` > 1) that was not in the paper.
