### ISSUE TITLE
ModuleNotFoundError: No module named 'gateloop_transformer'

### ISSUE THREAD

**Issue by Carrotsniper** [lucidrains/iTransformer#21]
I ran "pip install iTransformer",
but when importing, it said: ModuleNotFoundError: No module named 'gateloop_transformer'

**Comment by lucidrains** [comment]
@Carrotsniper my bad, try 0.5.4?

**Comment by Carrotsniper** [comment]
Thanks for your quick response.
I simply cloned the 'gateloop_transformer' repository, and it solved the problem.
Should have tried before asking...

**Comment by lucidrains** [comment]
@Carrotsniper nah my fault

everyone of my repo should just work with a pip install

**Comment by Carrotsniper** [comment]
Thank you if you can fix this when you have time.
