### ISSUE TITLE
ModuleNotFoundError: No module named 'iTransformer.iTransformerNormConditioned'

### ISSUE THREAD

**Issue by mkkk1112** [lucidrains/iTransformer#22]
(shy_py38) zhenningli@iotsc-zhenningli:~/shy$ /home/zhenningli/anaconda3/envs/shy_py38/bin/python /home/zhenningli/shy/DSTA2/test.py
Traceback (most recent call last):
  File "/home/zhenningli/shy/DSTA2/test.py", line 2, in <module>
    import iTransformer
  File "/home/zhenningli/anaconda3/envs/shy_py38/lib/python3.8/site-packages/iTransformer/__init__.py", line 10, in <module>
    from iTransformer.iTransformerNormConditioned import iTransformerNormConditioned
ModuleNotFoundError: No module named 'iTransformer.iTransformerNormConditioned'

I installed iTransformer using 'pip install Transformers' according to the readme. But when I run the example, I get an error and I cannot import iTransformer correctly. My torch version is 2.1.0 and CUDA version is 11.8. Looking forward to your answer, thank you very much.

**Comment by lucidrains** [comment]
@mkkk1112 oops, thanks for reporting!

**Comment by mkkk1112** [comment]
When I comment out the following code in __init__.py, the error disappears and it seems like it has no effect on normal operation,thanks for your reply!

# from iTransformer.iTransformerNormConditioned import iTransformerNormConditioned

**Comment by mkkk1112** [comment]
> @mkkk1112 oops, thanks for reporting!

When I comment out the following code in __init__.py, the error disappears and it seems like it has no effect on normal operation,thanks for your reply.

from iTransformer.iTransformerNormConditioned import iTransformerNormConditioned
