### ISSUE TITLE
Do iTransformer support Tensorflow instead of PyTorch?

### ISSUE THREAD

**Issue by ikhsansdqq** [lucidrains/iTransformer#26]
Dear @lucidrains, I have been testing your model for my final-year project, and thank God it works amazingly. I just wonder whether iTransformer already supports Tensorflow or will always use PyTorch.

**Comment by lucidrains** [comment]
@ikhsansdqq glad to hear! i'm afraid i vowed never to touch tensorflow after my last project with it.
