### ISSUE TITLE
Typo in Description under usage in Readme.md

### ISSUE THREAD

**Issue by meteoDaniel** [lucidrains/iTransformer#3]
Dear creators of iTransformer. 

I am really looking forward to Test in the next days. 

In your usage example, there might be a typo in the comment describing the dimensions of the output. 
The dimensions pred_length and variate have to change ?!

Best regards

**Comment by lucidrains** [comment]
the pred length is the forecast for all variates

**Comment by lucidrains** [comment]
I could have misunderstood the paper too, open to discussion

**Comment by meteoDaniel** [comment]
I mean this line in the Readme: 

```
# preds -> Dict[int, Tensor[batch, variate, pred_length]]
#       -> (12: (2, 12, 137), 24: (2, 24, 137), 36: (2, 36, 137), 48: (2, 48, 137))
```

I think it should be:

```
# preds -> Dict[int, Tensor[batch, pred_length, variate]]
#       -> (12: (2, 12, 137), 24: (2, 24, 137), 36: (2, 36, 137), 48: (2, 48, 137))
```

**Comment by lucidrains** [comment]
@meteoDaniel thanks!
